version: 2

models:
  - name: stg_us_large_airports
    columns:
      - name: id
        description: id of airport
        tests:
                - unique
                - not_null
      - name: ident
        description: IATA ident of airport
        tests:
                - unique
                - not_null

  - name: list_top_freq__pivot
